### ISSUE TITLE
Question of Evaluation protocol

### ISSUE THREAD

**Issue by LeeJ1Hyun** [vskadandale/vocalist#5]
Hi, I was impressed with your paper and code.
Well , I have a question in your paper .
The AVST[13] Accuracy , in table 1. Accuracy of lip synchronisation models in LRS2 , is different from AVST[13] paper's accuracy.
As far as I know, AVST[13] code is not released.

So did you get the AVST[13] accuracy by coding youself?

I'd appreciate it if you could reply.

**Comment by vskadandale** [comment]
Hi,

In AVST paper, you should be looking at table showing ablation on transformer depth (Table 3). The other table (Table 2) that you are looking at shows the results of AVST trained with variable length input. In fact, the results that we reported for AVST model are taken from the last row of Table 3. We contacted the main author of AVST paper who also confirmed that the scores reported in Table 3 are for models trained on 5 frames input but evaluated for different frame contexts based on the same evaluation method used in the Perfect Match paper. The same applies to our evaluation procedure since we only trained our model on 5 frame input in the case of LRS2. I strongly recommend that you read the papers (Perfect Match, AVST) to know more about the evaluation procedure.
